name: Deploy to EC2

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.79.228.222 '
            cd ~/Gongspot_Web &&
            git pull origin main &&
            pnpm install &&
            pnpm build &&
            sudo cp -r dist/* /var/www/html/ &&
            sudo systemctl reload nginx
          '
